[2023-11-14 18:23:46,869: INFO: main: this is for test porpose]
[2023-11-14 20:08:03,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-14 20:08:03,954: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 20:19:53,029: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-14 20:19:53,031: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 20:19:53,033: INFO: common: created directory at: artifacts]
[2023-11-14 20:19:53,035: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 20:19:53,036: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 20:20:16,316: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-18 09:47:46,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-18 09:47:46,178: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-18 09:47:46,180: INFO: common: created directory at: artifacts]
[2023-11-18 09:47:46,181: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-18 09:47:46,183: INFO: 4196335540: Downloading data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-18 09:48:11,423: INFO: 4196335540: Downloaded data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-19 10:11:04,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-19 10:11:04,043: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-19 10:11:04,048: INFO: common: created directory at: artifacts]
[2023-11-19 10:11:04,051: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-19 10:11:04,691: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-26 13:19:39,232: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-26 13:19:39,238: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-26 13:19:39,240: INFO: common: created directory at: artifacts]
[2023-11-26 13:19:39,242: INFO: common: created directory at: artifacts\training]
[2023-11-26 13:53:35,065: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-26 13:53:35,077: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-26 13:53:35,080: INFO: common: created directory at: artifacts]
[2023-11-26 13:53:35,094: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-26 13:53:35,096: INFO: 4196335540: Downloading data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-26 13:55:26,992: INFO: 4196335540: Downloaded data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-26 14:08:00,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-26 14:08:00,011: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-26 14:08:00,013: INFO: common: created directory at: artifacts]
[2023-11-26 14:08:00,015: INFO: common: created directory at: artifacts\training]
[2023-11-26 19:17:38,645: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-26 19:17:38,653: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-26 19:17:38,655: INFO: common: created directory at: artifacts]
[2023-11-26 19:18:10,342: INFO: common: json file saved at: scores.json]
[2023-11-26 19:18:15,396: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-26 19:18:16,905: INFO: builder_impl: Assets written to: C:\Users\meabh\AppData\Local\Temp\tmpdh0c4k97\model\data\model\assets]
[2023-11-26 19:29:22,807: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-26 19:29:22,818: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-26 19:29:22,820: INFO: common: created directory at: artifacts]
[2023-11-26 19:29:56,697: INFO: common: json file saved at: scores.json]
[2023-11-26 19:30:05,139: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-26 19:30:06,777: INFO: builder_impl: Assets written to: C:\Users\meabh\AppData\Local\Temp\tmpsjyjxylf\model\data\model\assets]
[2023-12-16 18:50:36,968: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.58.192:8080]
[2023-12-16 18:50:36,969: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-16 18:50:45,024: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 18:50:45] "GET / HTTP/1.1" 200 -]
[2023-12-16 18:51:35,406: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File ".\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\meabh\vs code projects\kidney-tumor-classification-dl-using-mlflow-cicd\src\cnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-16 18:51:35,417: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 18:51:35] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-16 18:55:22,377: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 18:55:22] "GET / HTTP/1.1" 200 -]
[2023-12-16 18:55:27,442: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File ".\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\meabh\vs code projects\kidney-tumor-classification-dl-using-mlflow-cicd\src\cnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-16 18:55:27,446: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 18:55:27] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-16 18:55:49,101: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 18:55:49] "GET / HTTP/1.1" 200 -]
[2023-12-16 18:56:17,808: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File ".\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\meabh\vs code projects\kidney-tumor-classification-dl-using-mlflow-cicd\src\cnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-16 18:56:17,814: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 18:56:17] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-16 18:58:11,505: INFO: stage01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-16 18:58:11,508: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 18:58:11,515: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 18:58:11,516: INFO: common: created directory at: artifacts]
[2023-12-16 18:58:11,516: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-16 18:58:11,517: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 18:58:37,086: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 18:58:37,365: INFO: stage01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-16 19:00:12,701: INFO: stage01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-16 19:00:12,704: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 19:00:12,707: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 19:00:12,708: INFO: common: created directory at: artifacts]
[2023-12-16 19:00:12,709: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-16 19:00:12,710: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 19:00:37,275: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 19:00:37,600: INFO: stage01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-16 19:02:41,459: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.58.192:8080]
[2023-12-16 19:02:41,460: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-16 19:02:44,042: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:02:44] "GET / HTTP/1.1" 200 -]
[2023-12-16 19:02:49,853: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File ".\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\meabh\vs code projects\kidney-tumor-classification-dl-using-mlflow-cicd\src\cnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-16 19:02:49,861: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:02:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-16 19:07:15,965: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-16 19:07:15,968: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 19:07:15,972: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 19:07:15,972: INFO: common: created directory at: artifacts]
[2023-12-16 19:07:15,973: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-16 19:07:15,973: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 19:07:40,968: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1JdOFjlz4nPTDpSV9EZJ_kW_cAZWc65fP/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 19:07:41,976: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-16 19:07:41,976: INFO: main: *******************]
[2023-12-16 19:07:41,977: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-16 19:07:41,981: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 19:07:41,983: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 19:07:41,983: INFO: common: created directory at: artifacts]
[2023-12-16 19:07:41,983: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-16 19:07:44,599: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-16 19:07:44,847: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-16 19:07:44,848: INFO: main: *******************]
[2023-12-16 19:07:44,848: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-16 19:07:44,852: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 19:07:44,855: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 19:07:44,856: INFO: common: created directory at: artifacts]
[2023-12-16 19:07:44,858: INFO: common: created directory at: artifacts\training]
[2023-12-16 19:12:13,776: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-16 19:12:13,776: INFO: main: *******************]
[2023-12-16 19:12:13,776: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-16 19:12:13,780: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 19:12:13,785: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 19:12:13,786: INFO: common: created directory at: artifacts]
[2023-12-16 19:12:32,171: INFO: common: json file saved at: scores.json]
[2023-12-16 19:12:32,171: INFO: common: json file saved at: scores.json]
[2023-12-16 19:12:32,172: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-16 19:13:36,049: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.58.192:8080]
[2023-12-16 19:13:36,051: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-16 19:13:40,347: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:13:40] "GET / HTTP/1.1" 200 -]
[2023-12-16 19:13:48,160: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File ".\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\meabh\vs code projects\kidney-tumor-classification-dl-using-mlflow-cicd\src\cnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\meabh\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-16 19:13:48,167: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:13:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-16 19:29:19,300: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.58.192:8080]
[2023-12-16 19:29:19,300: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-16 19:29:21,996: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:29:21] "GET / HTTP/1.1" 200 -]
[2023-12-16 19:29:31,494: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:29:31] "POST /predict HTTP/1.1" 200 -]
[2023-12-16 19:38:25,031: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:38:25] "GET / HTTP/1.1" 200 -]
[2023-12-16 19:38:36,933: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:38:36] "GET /train HTTP/1.1" 200 -]
[2023-12-16 19:38:36,972: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:38:36] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-12-16 19:38:46,682: INFO: _internal: 127.0.0.1 - - [16/Dec/2023 19:38:46] "GET / HTTP/1.1" 200 -]
